version: '3'

services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: "https://opensearch:9200"
    ports:
      - 5601:5601
    links:
      - opensearch
    networks:
      - sandbox

  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opensearch
    environment:
      - cluster.name=docker-cluster
      - node.name=os-node
      - cluster.initial_master_nodes=os-node
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $PWD/.local/opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - sandbox

  searcher:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: searcher
    environment:
      OPEN_SEARCH_ADDRESS: "https://opensearch:9200"
      USER_NAME: admin
      PASSWORD: admin
      PORT: 4646
    ports:
      - 4646:4646
    depends_on:
      - opensearch
    volumes:
      - .:/go/src/app
    networks:
      - sandbox

networks:
  sandbox: