name: Index Runner
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *"
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Send request to Example
        env:
          URL: ${{ secrets.INDEX_URL }}
        run: |
          python - <<EOF
          import requests
          import logging
          import traceback
          import sys
          
          try:
              response = requests.get('${{ env.URL }}')
              response.raise_for_status()
              logging.info('Request sent successfully')
          except Exception:
              logging.error(traceback.format_exc())
              sys.exit(1)
